Parser
cabouezzi/lira pull request #4
Opened 2023-08-18 04:08 UTC by cabouezzi

* IExpr interface and types following visitor pattern.  
* ASTPrinter class conforms to visitor interface to pretty print an expression. 
* Created Parser class that currently only parses single expressions
* Added shell script to automatically build and run a test file (named ExpressionTest.lira)

2023-08-18 15:11 UTC, MarioFares requested changes

2023-08-18 15:11 UTC, MarioFares commented on lira/ASTPrinter.cs
> +public class ASTPrinter: IExpr.IVisitor<string>
Put a space before the colon.

2023-08-18 15:11 UTC, MarioFares commented on lira/ASTPrinter.cs
> +    public ASTPrinter() {}
No need to put this now. An empty public constructor is automatically generated by the compiler if none is provided.

2023-08-18 15:11 UTC, MarioFares commented on lira/ASTPrinter.cs
> +    public string VisitLiteral(IExpr.Literal literal) => literal.Value == null ? "nil" : $"{literal.Value}";
Use `is null` and `is not null` to check for null.

2023-08-18 15:11 UTC, MarioFares commented on lira/IExpr.cs
> +// This is an auto-generated file
Remove.

2023-08-18 15:11 UTC, MarioFares commented on lira/IExpr.cs
> +	public interface IVisitor<T>
Fix the indentation in this one. The indentation in this file is off.

2023-08-18 15:11 UTC, MarioFares commented on lira/Main.cs
> +        if (expr == null)
Again, use `is null`.

2023-08-18 15:11 UTC, MarioFares commented on lira/Parser.cs
> +    public class ParserError: Exception {}
Space before colon.

2023-08-18 15:11 UTC, MarioFares commented on .gitignore
> +
You should add `.vscode` to `.gitignore`.

2023-08-18 15:16 UTC, cabouezzi commented on lira/IExpr.cs
> +// This is an auto-generated file
But it is an auto-generated file

2023-08-19 14:38 UTC, MarioFares approved these changes

2023-08-19 15:17 UTC, merged

2023-08-19 15:19 UTC, cabouezzi commented
![](https://64.media.tumblr.com/48c499de098eef81391e981f62568780/e4c7a3150cb27f91-36/s500x750/3c63f56720c6dfd508c5936b8aaa65f725567373.gif)